### ISSUE TITLE
Strange Update

### ISSUE THREAD

**Issue by kaspar-allenbach** [am-impact/amforms#105]
Hi.

Your latest update removed every field from every form :(
Was this really necessary?

**Comment by hubertprein** [comment]
Crap. No this was not necessary and definitely not intended either..

I'll come up with a fix.

**Comment by hubertprein** [comment]
Fixed for feature downloads. https://github.com/am-impact/amforms/commit/4b9649085842125f2af246ab5c9101e264ebe91a

Sorry for the inconvenience.

**Comment by rswhite7** [comment]
This doesn't seem to be fixed.  The fields are still missing from the submissions.  I reverted back to an older version of the plugin and they are still missing...

<img width="1440" alt="screen shot 2016-10-20 at 4 04 05 pm" src="https://cloud.githubusercontent.com/assets/13842870/19563001/d36ccb50-96de-11e6-8775-4fa1beb50dde.png">

**Comment by rswhite7** [comment]
Ah it seems that you have to reset all the fields to any pre-made forms!  Good thing I had a recent back up, but I imagine this to cause some major headaches to someone who updated before the fix :/

**Comment by hubertprein** [comment]
Yeah, totally overlooked when I wrote the migration file. Obviously tested it, but didn't see this part going terribly wrong.
